
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - default_network
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka
    networks:
      - default_network
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "TopicCurrency:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  producer:
    build: ./producer
    restart: always
    networks:
      - default_network
    environment:
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
    volumes:
      - ./producer:/app
    
    command: ["sleep", "infinity"]
    depends_on:
      - kafka

  consumer:
    build: ./consumer
    restart: always
    networks:
      - default_network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_USER}
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
    volumes:
      - ./consumer:/app
    
    command: ["sleep", "infinity"]
    depends_on:
      - kafka

networks:
  default_network:
    name: default_network